import {Suspense,useMemo,useRef} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Html,ContactShadows} from '@react-three/drei';
import * as THREE from 'three';
import {bridges,regions,type Region,type Point} from '../game/world';
const mat=(color:string)=>({color,roughness:.85,flatShading:true});
function Box({p,s,c,...props}: {p:Point;s:Point;c:string;[key:string]:any}){return <mesh position={p} castShadow receiveShadow {...props}><boxGeometry args={s}/><meshStandardMaterial {...mat(c)}/></mesh>}
function Tree({p,scale=1,pine=false}:{p:Point;scale?:number;pine?:boolean}){return <group position={p} scale={scale}><Box p={[0,.55,0]} s={[.17,1.1,.17]} c="#71543d"/>{pine?[0,1,2].map(i=><mesh key={i} position={[0,.9+i*.43,0]} castShadow><coneGeometry args={[.65-i*.13,1.2,7]}/><meshStandardMaterial {...mat(i%2?'#456d44':'#365d40')}/></mesh>):<><mesh position={[0,1.5,0]} castShadow><icosahedronGeometry args={[.85,1]}/><meshStandardMaterial {...mat('#788747')}/></mesh><mesh position={[.35,1.65,.1]} castShadow><icosahedronGeometry args={[.6,0]}/><meshStandardMaterial {...mat('#9a9b51')}/></mesh></>}</group>}
function House({p,c='#e5c89b',s=1,rot=0}:{p:Point;c?:string;s?:number;rot?:number}){return <group position={p} scale={s} rotation={[0,rot,0]}><Box p={[0,.6,0]} s={[1,1.2,.9]} c={c}/><mesh position={[0,1.38,0]} rotation={[0,Math.PI/4,0]} castShadow><coneGeometry args={[.89,.7,4]}/><meshStandardMaterial {...mat('#a55338')}/></mesh><Box p={[.26,1.6,.15]} s={[.16,.65,.16]} c="#a48068"/><Box p={[0,.29,.46]} s={[.22,.58,.025]} c="#4c514a"/>{[-.3,.3].map(x=><group key={x}><Box p={[x,.84,.46]} s={[.19,.25,.02]} c="#52747a"/><Box p={[x,.84,.48]} s={[.025,.25,.025]} c="#e4d9bb"/></group>)}<Box p={[0,.61,.48]} s={[1,.055,.03]} c="#876c50"/></group>}
function Cathedral(){return <group position={[-1.5,.62,-.4]}><Box p={[0,.9,0]} s={[1.3,1.8,1.8]} c="#bf8962"/><mesh position={[0,2,0]} rotation={[0,Math.PI/4,0]} castShadow><coneGeometry args={[1.4,.8,4]}/><meshStandardMaterial {...mat('#657873')}/></mesh><Box p={[-.6,1.35,.9]} s={[.63,2.7,.65]} c="#c99b72"/><mesh position={[-.6,3.05,.9]} castShadow><coneGeometry args={[.48,1.1,4]}/><meshStandardMaterial {...mat('#416d6a')}/></mesh><Box p={[-.6,3.7,.9]} s={[.035,.38,.035]} c="#dabc70"/><Box p={[-.6,3.74,.9]} s={[.2,.035,.035]} c="#dabc70"/>{[-.43,.43].map(x=><Box key={x} p={[x,1.1,1]} s={[.2,.7,.04]} c="#496269"/>)}</group>}
function Bird({i}:{i:number}){const ref=useRef<THREE.Group>(null);const l=useRef<THREE.Mesh>(null);const r=useRef<THREE.Mesh>(null);useFrame(({clock})=>{const t=clock.elapsedTime*.25+i*1.7;if(ref.current){ref.current.position.set(Math.sin(t)*(6+i*.3),4+Math.sin(t*1.6)*.6,Math.cos(t)*(4+i*.3));ref.current.rotation.y=-t;}if(l.current&&r.current){l.current.rotation.z=Math.sin(t*19)*.45;r.current.rotation.z=-Math.sin(t*19)*.45;}});return <group ref={ref}><mesh ref={l} position={[-.15,0,0]}><boxGeometry args={[.32,.035,.12]}/><meshStandardMaterial color="#f7e9c8"/></mesh><mesh ref={r} position={[.15,0,0]}><boxGeometry args={[.32,.035,.12]}/><meshStandardMaterial color="#f7e9c8"/></mesh></group>}
function Water(){const ref=useRef<THREE.Mesh>(null);const geo=useMemo(()=>{const g=new THREE.PlaneGeometry(23,17,65,45);g.rotateX(-Math.PI/2);return g},[]);useFrame(({clock})=>{const a=geo.attributes.position;for(let i=0;i<a.count;i++)a.setY(i,Math.sin(a.getX(i)*1.8+clock.elapsedTime*1.4)*.025+Math.cos(a.getZ(i)*2.2+clock.elapsedTime)*.02);a.needsUpdate=true;geo.computeVertexNormals();});return <mesh ref={ref} geometry={geo} position={[0,.14,0]} receiveShadow><meshStandardMaterial color="#388f99" roughness={.35} metalness={.2} flatShading/></mesh>}
function Ripples(){const ref=useRef<THREE.Group>(null);useFrame(({clock})=>{if(ref.current)ref.current.position.x=Math.sin(clock.elapsedTime*.4)*.4});return <group ref={ref}>{Array.from({length:45},(_,i)=><Box key={i} p={[-10+(i*3.17)%20,.2,i%2?2.7+(i%3)*.25:-3.2+(i%3)*.25]} s={[.25+(i%4)*.15,.008,.025]} c="#92c8bd"/>)}</group>}
function Waterfalls(){const drops=useRef<THREE.Group>(null);useFrame(({clock})=>{drops.current?.children.forEach((m,i)=>{m.position.y=.1-((clock.elapsedTime*(.8+i%3*.2)+i*.19)%2.7);m.scale.y=.7+Math.sin(clock.elapsedTime*4+i)*.2;});});return <group><group ref={drops}>{Array.from({length:22},(_,i)=><mesh key={i} position={[-11.55-(i%3)*.035,0,-3.8+(i%11)*.15]}><boxGeometry args={[.055,.48,.09]}/><meshStandardMaterial color={i%3?'#7bc6c7':'#d5efdc'} transparent opacity={.72}/></mesh>)}</group>{Array.from({length:9},(_,i)=><mesh key={i} position={[-11.6+(i%3)*.14,-2.5,-3.6+i*.15]}><icosahedronGeometry args={[.17+(i%3)*.05,0]}/><meshStandardMaterial color="#c8e9da" transparent opacity={.7}/></mesh>)}</group>}
function Clouds(){const ref=useRef<THREE.Group>(null);useFrame(({clock})=>{if(ref.current)ref.current.position.x=Math.sin(clock.elapsedTime*.045)*1.5});return <group ref={ref}>{[-7,7].map((x,i)=><group key={x} position={[x,5.8+i,-5+i*8]}>{[0,1,2].map(j=><mesh key={j} position={[j*.5,Math.sin(j)*.15,0]}><icosahedronGeometry args={[.48+j*.05,1]}/><meshStandardMaterial color="#cad9cf" transparent opacity={.5} flatShading/></mesh>)}</group>)}</group>}
function Boat({z,x=0}:{z:number;x?:number}){const ref=useRef<THREE.Group>(null);useFrame(({clock})=>{if(ref.current){ref.current.position.x=x+Math.sin(clock.elapsedTime*.11)*1.4;ref.current.rotation.z=Math.sin(clock.elapsedTime*1.2)*.025;}});return <group ref={ref} position={[x,.32,z]}><mesh rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.27,.2,1.2,5]}/><meshStandardMaterial color="#614d37"/></mesh><Box p={[0,.47,0]} s={[.035,.9,.035]} c="#705c40"/><mesh position={[.19,.63,0]}><planeGeometry args={[.36,.55]}/><meshStandardMaterial color="#eee0b7" side={THREE.DoubleSide}/></mesh></group>}
function Person({position,color='#c8884c'}:{position:Point;color?:string}){return <group position={position}><mesh position={[0,.29,0]} castShadow><coneGeometry args={[.16,.48,6]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,.61,0]} castShadow><sphereGeometry args={[.105,8,6]}/><meshStandardMaterial color="#d9b48a"/></mesh><mesh position={[0,.72,0]}><cylinderGeometry args={[.12,.17,.07,7]}/><meshStandardMaterial color="#403f37"/></mesh>{[-.07,.07].map(x=><Box key={x} p={[x,.07,0]} s={[.06,.18,.08]} c="#3b4848"/>)}</group>}
export type Journey={points:Point[];key:number};
function Traveller({journey,onArrive}:{journey:Journey;onArrive:()=>void}){const ref=useRef<THREE.Group>(null);const step=useRef(0);const key=useRef(-1);useFrame((_,dt)=>{if(!ref.current)return;if(key.current!==journey.key){key.current=journey.key;step.current=1;ref.current.position.fromArray(journey.points[0]);}const target=journey.points[step.current];if(target){const v=new THREE.Vector3(...target);const delta=v.sub(ref.current.position);if(delta.length()<.07){step.current++;if(step.current===journey.points.length)onArrive();}else{ref.current.position.add(delta.normalize().multiplyScalar(Math.min(dt,.04)*2.8));ref.current.rotation.y=Math.atan2(delta.x,delta.z);}}});return <group ref={ref}><Person position={[0,0,0]} color="#ce703c"/><mesh position={[0,.025,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.25,.32,24]}/><meshBasicMaterial color="#ffe1a1" side={THREE.DoubleSide}/></mesh><mesh position={[0,1.1,0]} rotation={[0,0,Math.PI]}><coneGeometry args={[.1,.18,4]}/><meshBasicMaterial color="#ffcf75"/></mesh></group>}
function Bridge({b,used,active,onCross}:{b:typeof bridges[number];used:boolean;active:boolean;onCross:(id:number)=>void}){const horizontal=b.id===7;const length=horizontal?b.b[0]-b.a[0]:Math.abs(b.b[2]-b.a[2]);const center:Point=[(b.a[0]+b.b[0])/2,.62,(b.a[2]+b.b[2])/2];return <group position={center} rotation={[0,horizontal?Math.PI/2:0,0]} onClick={e=>{e.stopPropagation();onCross(b.id)}} onPointerOver={()=>document.body.style.cursor='pointer'} onPointerOut={()=>document.body.style.cursor='auto'}><Box p={[0,0,0]} s={[.83,.15,length+.2]} c={used?'#bd9960':'#d2b18a'}/>{Array.from({length:10},(_,i)=><Box key={i} p={[0,.085,-length/2+i*length/9]} s={[.8,.025,.04]} c="#a58b69"/>)}{[-.46,.46].map(x=><group key={x}><Box p={[x,.27,0]} s={[.065,.07,length+.25]} c="#b99772"/>{[-1,0,1].map(z=><Box key={z} p={[x,.12,z*length/2]} s={[.1,.4,.1]} c="#ad8e69"/>)}<Box p={[x*.7,-.28,0]} s={[.22,.55,.36]} c="#807d67"/></group>)}<Html position={[0,.73,0]} center distanceFactor={27}><button className={`bridge-marker ${used?'crossed':''} ${active?'available':''}`} aria-label={`Cross ${b.name}${used?', already crossed':''}`} onClick={e=>{e.stopPropagation();onCross(b.id)}}>{used?'✓':b.id}</button></Html></group>}
function Landscape(){const trees=useMemo(()=>Array.from({length:52},(_,i)=>({x:-10.5+(i%13)*1.75,z:i<26?-7.3+(Math.floor(i/13))*.8:6.25+Math.floor((i-26)/13)*1.05,s:.65+(i*7%9)*.06})),[]);return <><Box p={[0,-.7,0]} s={[23,1.4,17]} c="#416366"/><Box p={[0,-1.43,0]} s={[22.9,.1,16.9]} c="#26454c"/><Water/><Ripples/><Waterfalls/><Clouds/>{[{p:[0,.25,-6.4],s:[23,.75,4.2]},{p:[0,.25,6.4],s:[23,.75,4.2]},{p:[-2.5,.25,0],s:[8.4,.75,3.4]},{p:[7.95,.25,0],s:[7.1,.75,3.4]}].map((l,i)=><group key={i}><Box p={l.p as Point} s={l.s as Point} c="#84966d"/><Box p={[l.p[0],.08,l.p[2]]} s={[l.s[0]+.08,.55,l.s[2]+.08]} c="#8c8970"/></group>)}{[-5.1,5.1].map(z=><Box key={z} p={[0,.641,z]} s={[22,.025,.55]} c="#c2b48b"/>)}<Box p={[-2.5,.641,0]} s={[8,.025,.55]} c="#c2b48b"/><Box p={[8,.641,0]} s={[7,.025,.55]} c="#c2b48b"/>{trees.map((t,i)=><Tree key={i} p={[t.x,.64,t.z]} scale={t.s} pine={i%3===0}/>)}{Array.from({length:18},(_,i)=><House key={i} p={[-9+(i%9)*2.2,.65,i<9?-6.1:6.1]} s={.72+(i%3)*.09} c={['#e4c69b','#d7ba91','#bba789','#d4cbb0'][i%4]} rot={i<9?0:Math.PI}/>)}{[-5.4,-4.2,.7,5.3,7.8,9.3].map((x,i)=><House key={x} p={[x,.65,i%2?-.85:.85]} s={.65} c="#d8c5a1"/>)}<Cathedral/><Boat z={-3} x={-7}/><Boat z={3} x={3}/>{Array.from({length:7},(_,i)=><Bird key={i} i={i}/>)}{Array.from({length:11},(_,i)=><Person key={i} position={[-9+i*1.8,.65,i%2?-5:5]} color={['#5d7580','#926e52','#877c55'][i%3]}/>)}{[-10.3,10.4].map(x=><group key={x}><mesh position={[x,1,-7]} castShadow><dodecahedronGeometry args={[1.2,0]}/><meshStandardMaterial {...mat('#87908b')}/></mesh><Tree p={[x,.65,4]} scale={1.25} pine/></group>)}</>}
export default function Konigsberg({at,used,onCross,journey,onArrive,resetKey}:{at:Region;used:number[];onCross:(id:number)=>void;journey:Journey;onArrive:()=>void;resetKey:number}){return <Canvas shadows dpr={[1,1.75]} orthographic camera={{position:[20,24,27],zoom:32,near:.1,far:150}} gl={{antialias:true}}><color attach="background" args={['#17333d']}/><fog attach="fog" args={['#17333d',52,105]}/><ambientLight intensity={1.4}/><hemisphereLight args={['#e4f1ec','#6d7b69',1.3]}/><directionalLight position={[-10,20,8]} intensity={3} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-18} shadow-camera-right={18} shadow-camera-top={18} shadow-camera-bottom={-18} shadow-normalBias={.035}/><Suspense fallback={null}><group position={[0,-.6,0]}><Landscape/>{bridges.map(b=><Bridge key={b.id} b={b} used={used.includes(b.id)} active={!used.includes(b.id)&&(b.from===at||b.to===at)} onCross={onCross}/>)}<Traveller journey={journey} onArrive={onArrive}/></group><ContactShadows position={[0,-2.2,0]} opacity={.25} scale={40} blur={2} far={8}/></Suspense><OrbitControls key={resetKey} makeDefault target={[0,0,0]} minZoom={19} maxZoom={80} minPolarAngle={.25} maxPolarAngle={1.35} enableDamping/></Canvas>}
