import {useState, useCallback, useEffect, useRef, Component, type ReactNode} from 'react';
import {Compass,RotateCcw,Map,BookOpen,ArrowUpRight,ChevronRight,VolumeX,Footprints,X,Move,ZoomIn} from 'lucide-react';
import Konigsberg,{type Journey} from './scenes/Konigsberg';
import {bridges,regions,availableBridges,cross,degree,type Region} from './game/world';
class SceneBoundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true}}render(){return this.state.error?<div className="scene-error">The 3D world could not start. Enable browser graphics acceleration and reload. You can still explore the bridge challenge using the route buttons.</div>:this.props.children}}
function Graph({at,used,onCross}:{at:Region;used:number[];onCross:(id:number)=>void}){const pos:Record<Region,[number,number]>={north:[115,45],south:[115,235],island:[65,140],east:[250,140]};return <svg viewBox="0 0 330 280" role="img" aria-label="Four land regions connected by seven bridges"><title>The Königsberg graph</title>{bridges.map(b=>{const a=pos[b.from],c=pos[b.to];const mid=[(a[0]+c[0])/2,(a[1]+c[1])/2];const offset=b.id<5?(b.id<3?-30:30):0;return <g key={b.id} onClick={()=>onCross(b.id)} className="graph-edge"><path d={`M${a} Q${mid[0]+offset},${mid[1]} ${c}`} stroke={used.includes(b.id)?'#d8ad68':'#8cb0b2'} fill="none" strokeWidth="4"/><text x={mid[0]+offset*.5} y={mid[1]-7} fill="#e9d6b0" fontSize="14">{b.id}</text></g>})}{Object.entries(pos).map(([r,p])=><g key={r}><circle cx={p[0]} cy={p[1]} r="23" fill={at===r?'#dfba79':'#294952'} stroke="#c5d2ca"/><text x={p[0]} y={p[1]+5} textAnchor="middle" fill={at===r?'#17333d':'#f4e9d1'} fontSize="16">{degree(r as Region)}</text><text x={p[0]} y={p[1]+42} textAnchor="middle" fill="#d3dfd6" fontSize="13">{regions[r as Region].name}</text></g>)}</svg>}
export default function App(){const [at,setAt]=useState<Region>('north');const [used,setUsed]=useState<number[]>([]);const [moving,setMoving]=useState(false);const [message,setMessage]=useState('Your walk begins on the north bank. Choose a glowing bridge.');const [journal,setJournal]=useState(false);const [graph,setGraph]=useState(false);const [resetKey,setResetKey]=useState(0);const [journey,setJourney]=useState<Journey>({points:[regions.north.position],key:0});const [history,setHistory]=useState<{at:Region;used:number[]}[]>([]);
const available=availableBridges(at,used);const stuck=available.length===0&&used.length>0;
const onCross=useCallback((id:number)=>{if(moving)return;const result=cross(at,used,id);if(!result){setMessage(used.includes(id)?'You have already crossed that bridge. Try another route, or retrace your last step.':'That bridge is on another bank. Choose a bridge connected to your current location.');return;}const b=bridges.find(b=>b.id===id)!;const forward=b.from===at;setHistory(h=>[...h,{at,used}]);setMoving(true);setJourney(j=>({points:[regions[at].position,forward?b.a:b.b,forward?b.b:b.a,regions[result.at].position],key:j.key+1}));setAt(result.at);setUsed(result.used);setMessage(`Crossing ${b.name}…`);},[at,used,moving]);
const onArrive=useCallback(()=>{setMoving(false);setMessage(availableBridges(at,used).length?`You reached ${regions[at].name.toLowerCase()}. Where next?`:'No unused bridge leads away from here. Is it your route—or the city itself?');},[at,used]);
function restart(start:Region='north'){setAt(start);setUsed([]);setHistory([]);setMoving(false);setJourney(j=>({points:[regions[start].position],key:j.key+1}));setMessage(`A fresh walk from ${regions[start].name.toLowerCase()}. Each bridge, exactly once.`);}
function undo(){const prev=history.at(-1);if(!prev||moving)return;setAt(prev.at);setUsed(prev.used);setHistory(h=>h.slice(0,-1));setJourney(j=>({points:[regions[prev.at].position],key:j.key+1}));setMessage('One step back. Try another bridge.');}
const toolState=useRef({at,used,moving,connectionsVisible:graph});toolState.current={at,used,moving,connectionsVisible:graph};
useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();const tools=[{name:'read_bridge_walk',description:'Read the current bank, crossed bridges and available next crossings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...toolState.current,available:availableBridges(toolState.current.at,toolState.current.used).map(b=>({id:b.id,name:b.name}))})},{name:'show_bridge_connections',description:'Open the mathematical connections overlay in the visible game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(input===null||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');setGraph(true);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {connectionsVisible:true};}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return ()=>lifecycle.abort();},[]);
return <main className="game"><div className="world"><SceneBoundary><Konigsberg at={at} used={used} onCross={onCross} journey={journey} onArrive={onArrive} resetKey={resetKey}/></SceneBoundary></div><header className="topbar"><a className="brand" href="#" aria-label="Mercator home"><Compass size={30}/><span>MERCATOR<small>A WORLD OF MATHEMATICS</small></span></a><div className="chapter"><span className="tiny-label">CHAPTER 01</span><span>The beginning of a new way to think</span></div><button className={`icon-button ${journal?'selected':''}`} onClick={()=>setJournal(!journal)} aria-label="Open field journal"><BookOpen size={20}/></button></header>
<section className="scene-title"><div className="eyebrow"><span/> PRUSSIA · 18TH CENTURY</div><h1>The seven bridges<br/>of Königsberg</h1><p>One city. Seven bridges.<br/>A question that changed mathematics.</p></section>
<aside className="challenge"><div className="eyebrow"><Footprints size={15}/> YOUR FIRST WALK</div><h2>Every bridge.<br/>Only once.</h2><p>Can you cross all seven bridges without crossing any of them twice?</p><div className="progress-heading"><span>BRIDGES CROSSED</span><strong>{used.length}<em> / 7</em></strong></div><div className="bridge-progress">{bridges.map(b=><span key={b.id} className={used.includes(b.id)?'done':''}>{used.includes(b.id)?'✓':b.id}</span>)}</div><div className="location"><span className="location-dot"/><span>{regions[at].name}</span><small>{moving?'Walking…':'You are here'}</small></div><p className="status" aria-live="polite">{message}</p><div className="route-options">{available.map(b=><button key={b.id} disabled={moving} onClick={()=>onCross(b.id)}><span className="route-number">{b.id}</span>{b.name}<ChevronRight size={15}/></button>)}</div>{stuck&&!moving&&<button className="primary-button" onClick={()=>{setGraph(true);setJournal(true)}}>Look beneath the city <ArrowUpRight size={16}/></button>}<div className="walk-actions"><button onClick={undo} disabled={!history.length||moving}>Undo crossing</button><button onClick={()=>restart()}><RotateCcw size={14}/> New walk</button></div></aside>
<div className="world-controls"><button className={graph?'selected':''} onClick={()=>setGraph(!graph)}><Map size={17}/><span>{graph?'Hide connections':'See connections'}</span></button><button onClick={()=>setResetKey(k=>k+1)} aria-label="Reset camera"><Compass size={19}/></button></div>
{graph&&<section className="graph-panel"><div className="panel-heading"><span>THE CITY, SIMPLIFIED</span><button onClick={()=>setGraph(false)} aria-label="Close graph"><X size={17}/></button></div><Graph at={at} used={used} onCross={onCross}/><p>Land becomes a point. A bridge becomes a line. Numbers count the connections.</p></section>}
{journal&&<aside className="journal"><div className="panel-heading"><span>YOUR FIELD JOURNAL</span><button onClick={()=>setJournal(false)} aria-label="Close journal"><X size={20}/></button></div><span className="eyebrow">DISCOVERY 01 · CONNECTIONS</span><h2>What if the route<br/>is impossible?</h2><p>Every time you enter a piece of land and leave it, you use a pair of bridges.</p><p>Only the start and finish can have an unpaired crossing. So a walk using every bridge once can have <strong>at most two places with an odd number of connections.</strong></p><div className="degree-grid">{Object.keys(regions).map(r=><div key={r}><strong>{degree(r as Region)}</strong><span>{regions[r as Region].name}</span></div>)}</div><p>Königsberg has four. No choice of starting point can make the seven-bridge walk work.</p><button className="primary-button" onClick={()=>{setGraph(true);setJournal(false)}}>See the mathematical map <ArrowUpRight size={17}/></button><h3>Try a different starting point</h3><div className="start-options">{Object.keys(regions).map(r=><button key={r} onClick={()=>{restart(r as Region);setJournal(false)}}>{regions[r as Region].name}</button>)}</div><div className="historical-note"><strong>A note from the archive</strong><p>Euler’s work on this problem laid foundations for graph theory. This miniature preserves the seven-bridge connections; its buildings, landscape, and costumes are illustrative.</p><a href="https://mathshistory.st-andrews.ac.uk/Extras/Konigsberg/" target="_blank" rel="noreferrer">Read the historical account ↗</a></div></aside>}
<footer><span><span className="live-dot"/> A LIVING ATLAS</span><div><span><Move size={13}/> Drag to orbit</span><span><ZoomIn size={13}/> Scroll to zoom</span><span>Click a numbered bridge to walk</span></div><span className="coordinates">54°42′ N &nbsp; 20°30′ E</span></footer></main>}
